site_name: Linux Basics & CLI Course
site_url: "https://cnoam.github.io/linux101/"
theme:
  name: material
  custom_dir: overrides


docs_dir: docs
extra_css:
  - css/comment.css

extra_javascript:
  - js/comment.js


plugins:
  - i18n:
      default_language: en  # which language to serve at “/”
      docs_structure: suffix
      languages:
        - locale: en
          name: English
          build: true
          default: true       # <— mark this as the “/” site
        - locale: he
          name: עברית
          build: true
        # - locale: ar
        #   name: العربية
        #   build: true

        
nav:
  - Home: index.md
  - "01: Intro" : 01/ch_01.md
  - "02: The file system": 02/ch_02.md
  - "03: Working with files" : 03/ch_03.md
  - "04: File permissions" : 04/ch_04.md
  - "05: Basic command" : 05/ch_05.md
  - "06: Text processing" : 06/ch_06.md
  - "07: Advanced text processing" : 07/ch_07.md
  - "08: User/groups" : 08/ch_08.md
  - "09: Package management" : 09/ch_09.md
  - "10: Networking" : 10/networking.md
  #- Chapter 11: 11/ch_11.md

# Include image assets
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - codehilite
  - footnotes
  - tables

